### ISSUE TITLE
The key type dropdown should show a drop-down indicator like a triangle

### ISSUE THREAD

**Issue by obra** [keyboardio/chrysalis-bundle-keyboardio#85]
![image](https://user-images.githubusercontent.com/45416/50310921-58811b00-0458-11e9-8b2d-61f6fab7b9ec.png)

**Comment by algernon** [comment]
Hm.. this will be a tougher one, because the UI library we use doesn't have a widget like that out of the box. [Material design](https://material.io/design/components/menus.html#exposed-dropdown-menu) mentions dropdowns as a special case of Menu, however.

It shouldn't be *too* hard to add that little dropdown indicator, but it will take a bit longer, 'cos it's not just using another widget.

**Comment by obra** [comment]
even adding a ... after the letters for now might help. and coloring it the theme color maybe?

**Comment by algernon** [comment]
That should be much easier

**Comment by algernon** [comment]
Turns out adding a triangle there was easier than coloring. :)
